version: '3.8'  

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@22word2710
      MYSQL_DATABASE: travel_agency
      MYSQL_USER: root
      MYSQL_PASSWORD: P@22word2710
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  react:
    build: ./client  
    ports:
      - "3000:3000"
    depends_on:
      web:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_data:
