# Generated by Django 5.1.2 on 2024-11-04 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_groups_alter_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='id',
        ),
        migrations.AddField(
            model_name='vacation',
            name='VacationPicture',
            field=models.ImageField(default='default_image.png', upload_to='VacationPicture/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='countryId',
            field=models.ForeignKey(db_column='countryId', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='description',
            field=models.CharField(default='media/default_vacation.jpg', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='endDate',
            field=models.DateField(default='2025-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='startDate',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='vacationId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='country',
            table='countries',
        ),
        migrations.AlterModelTable(
            name='vacation',
            table='vacations',
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('roleId', models.ForeignKey(db_column='roleId', on_delete=django.db.models.deletion.CASCADE, to='core.rolemodel')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.usermodel'),
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('likesId', models.AutoField(primary_key=True, serialize=False)),
                ('vacationId', models.ForeignKey(db_column='vacationId', on_delete=django.db.models.deletion.CASCADE, to='core.vacation')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='core.usermodel')),
            ],
            options={
                'db_table': 'likes',
                'unique_together': {('userId', 'vacationId')},
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
